apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mycloudstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mycloudstorage
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
volumeBindingMode: WaitForFirstConsumer