apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

---
# Google Cloud:
apiVersion: v1
kind: StorageClass
metadata:
  name: cloud-ssd
spec:
  storageClassName: cloud-ssd
  type:
